apiVersion: v1
entries:
  pythonapp:
  - apiVersion: v2
    created: "2025-04-12T18:36:49.650112773Z"
    description: A Helm chart for Kubernetes
    digest: a978efa67f0cf69682ed6589c3598ec918d1c87c2ecf69eb01c7b1da1632e4cf
    name: pythonapp
    type: application
    urls:
    - https://aditya1234556.github.io/Terraform-Terragrunt/HELM/helmpackage/pythonapp-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    created: "2025-04-12T18:36:49.650528265Z"
    description: A Helm chart for Kubernetes
    digest: 9c08d527cb759213f3d1cc49cf9cd98bb1f5d95a76773891731c4a3a71c63aa2
    name: pythonapp
    type: application
    urls:
    - https://aditya1234556.github.io/Terraform-Terragrunt/HELM/helmpackage/Terraform-Terragrunt/pythonapp-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-12T18:36:49.649582668Z"
